export {default as Footer} from './footer/footer'
export {default as Header} from './header/header'
export {default as FormSuscript} from './FormSuscript/FormSuscript'
export {default as ImageContainer} from './imageContainer/imageContainer' 
export * as slider from './sliders' 
export {default as Video} from './video/videoComponent'