import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/components/frontend/styles/global-styles.scss";
import { Footer } from "@/components/frontend/footer/footer";
import Header from "@/components/frontend/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Backend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
